name: "Snapshot Patch for Bump Version"
description: "Patch version for snapshot"

inputs:
  working-directory:
    description: "The directory containing the `.bumpversion.cfg` file."
    required: false
    default: "."
outputs:
  release-version:
    description: "The bumped version of your project."
    value: ${{ steps.bump-version.outputs.new-version }}
  old-version:
    description: "The old version in your `.bumpversion.cfg` file."
    value: ${{ steps.bump-version.outputs.old-version }}

runs:
  using: "composite"
  steps:
    - name: Set up bumpversion
      run: |
        pipx install bump2version
      shell: bash

    - name: Bump version
      id: bump-version
      run: |
        echo "old-version=$(python -c "from configparser import ConfigParser; cfg = ConfigParser(); cfg.read('.bumpversion.cfg'); print(cfg['bumpversion']['current_version'])")" >> "$GITHUB_OUTPUT"
        bump2version --allow-dirty --no-tag --no-commit patch
        echo "new-version=$(python -c "from configparser import ConfigParser; cfg = ConfigParser(); cfg.read('.bumpversion.cfg'); print(cfg['bumpversion']['current_version'])")" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
