name: "Setup credentials"
description: "Setup credentials for GCloud and GKE"
inputs:
  gke-service-account:
    description: "GKE service account key for authentication"
    required: true
  gke-project:
    description: "GKE project id for authentication"
    required: true
  gke-region:
    description: "GKE region for authentication"
    required: true
  gke-cluster:
    description: "GKE cluster for authentication"
    required: true
  gcloud-sdk-version:
    description: "GCloud SDK version"
    default: "376.0.0"
    required: false
runs:
  using: "composite"
  steps:
    - name: Authenticate at GCloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.gke-service-account }}

      # HACK: workaround for warning
      # There are other instances of Google Cloud tools on your system PATH.
      # Please remove the following to avoid confusion or accidental invocation:

      #   /usr/lib/google-cloud-sdk/bin/gcloud
      # /usr/lib/google-cloud-sdk/bin/anthoscli
      # /usr/lib/google-cloud-sdk/bin/docker-credential-gcloud
      # /usr/lib/google-cloud-sdk/bin/bq
      # /usr/lib/google-cloud-sdk/bin/gsutil
      # /usr/lib/google-cloud-sdk/bin/git-credential-gcloud.sh
    - name: Remove preinstalled GCloud SDK
      shell: bash
      run: rm -rf /usr/lib/google-cloud-sdk || true

    - name: Setup GCloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: ${{ inputs.gcloud-sdk-version }}
        project_id: ${{ inputs.gke-project }}

    - name: Setup authentication
      shell: bash
      run: |
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION" --project "$GKE_PROJECT"
      env:
        GKE_REGION: ${{ inputs.gke-region }}
        GKE_CLUSTER: ${{ inputs.gke-cluster }}
        GKE_PROJECT: ${{ inputs.gke-project }}
