name: "Publish Docker image"
description: "Publish Docker image from downloaded artifact to any host"

inputs:
  docker-registry:
    description: "Host where the image should be pushed to."
    required: false
    default: ""
  image-namespace:
    description: "Namespace of Docker image."
    required: false
    default: ""
  image-name:
    description: "Name of Docker image."
    required: false
    default: "${{ github.event.repository.name }}"
  image-tag:
    description: "Tag of Docker image."
    required: false
    default: "pipeline-${{ github.run_id }}-git-${GITHUB_SHA::8}"
  image-artifact-name:
    description: "Name of the artifact that contains the Docker image.tar file to push, see https://github.com/actions/upload-artifact."
    required: false
    default: "image-artifact"
  working-directory:
    description: "Working directory for your Docker artifacts."
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Download Docker image tar artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.image-artifact-name }}
        path: ${{ runner.temp }}/docker-build

    # setup-buildx action will create and boot a builder using by default the docker-container driver.
    # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    # Replace default image tag on pull requests, because a GitHub commit sha works in a differnt way for pull requests 
    # See https://github.com/orgs/community/discussions/25191#discussioncomment-3246770
    - name: Replace tag 
      id: replace-tag
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" && "${{ inputs.image-tag }}" == "pipeline-${{ github.run_id }}-git-${GITHUB_SHA::8}" ]]; then
            pullRequestSha="${{ github.event.pull_request.head.sha }}"
            echo "tag=pipeline-${{ github.run_id }}-git-${pullRequestSha::8}" >> "$GITHUB_OUTPUT"
        fi

        echo "tag=${{ inputs.image-tag }}" >> "$GITHUB_OUTPUT 

    - name: Load image
      run: |
        if [[ $(ls -1 ${{ runner.temp }}/docker-build/*.tar 2>/dev/null | wc -l) != 1 ]]; then
          >&2 echo "Error: A single image tar file is needed in the downloaded artifact. You can upload one before using this action: https://github.com/actions/upload-artifact."
          exit 1
        fi

        docker load --input ${{ runner.temp }}/docker-build/*.tar
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Publish image
      uses: bakdata/ci-templates/actions/docker-push@1.30.0
      with:
        docker-registry: ${{ inputs.docker-registry }}
        image-namespace: ${{ inputs.image-namespace }}
        image-name: ${{ inputs.image-name }}
        image-tag: ${{ steps.replace-tag.outputs.tag }}
        working-directory: ${{ inputs.working-directory }}
