name: "Publish Docker image"
description: "Use a Dockerfile to publish image to any host"

inputs:
  image-tag:
    description: "Tag of the image to be pushed."
    required: true
  image-name:
    description: "Name of Docker image (Default is the repository name)."
    required: true
  publisher:
    description: "Publisher to prefix Docker image (e.g. 'my-publisher')."
    required: true
  username:
    description: "Username for the Docker registry login."
    required: true
  password:
    description: "Password for the Docker registry login."
    required: true
  working-directory:
    description: "Path of the directory containing the Dockerfile."
    required: true
  docker-registry:
    description: "Host where the image should be pushed to."
    required: true
  github-token:
    description: "Github token."
    required: true
  ref:
    description: "Ref to checkout"
    required: false
    default: ${{ github.event.repository.default_branch }}
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.github-token }}

    # setup-buildx action will create and boot a builder using by default the docker-container driver.
    # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Login to the Registry
      uses: "docker/login-action@v2.1.0"
      with:
        registry: "${{ inputs.docker-registry }}"
        username: "${{ inputs.username }}"
        password: "${{ inputs.password }}"

    - name: Build and push
      uses: docker/build-push-action@v3.2.0
      with:
        context: "${{ inputs.working-directory }}"
        push: true
        tags: |
          ${{ inputs.docker-registry }}/${{ inputs.publisher }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          ${{ inputs.docker-registry }}/${{ inputs.publisher }}/${{ inputs.image-name }}:latest
