name: "Checkout repository"
description: "Composite action for checking out a repository"
inputs:
  lfs:
    description: "Describes if the repository is using any LFS files"
    required: false
    default: "false"
  cache:
    description: "Describes if the repository is using any LFS files"
    required: false
    default: "true"

outputs:
  lfs-cache-hit:
    description: "A boolean value to indicate an exact match was found for the key."
    value: ${{ steps.cache-lfs.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Create LFS file list
      if: ${{ inputs.lfs == 'true'}}
      run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id

    - name: LFS Cache
      if: ${{ inputs.lfs == 'true' && inputs.cache == 'true' }}
      id: cache-lfs
      uses: actions/cache@v3
      with:
        path: .git/lfs/objects
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
        restore-keys: |
          ${{ runner.os }}-lfs-

    - name: Git LFS Pull
      if: ${{ inputs.lfs == 'true'}}
      run: git lfs pull
