name: "Release Java artifacts"
description: "Release Java Maven artifacts on Github"

inputs:
  github-username:
    description: "GitHub username for requesting changes from API."
    required: true
  github-token:
    description: "GitHub token for requesting changes from API."
    required: true
  java-distribution:
    description: "Java distribution to be installed. (Default is microsoft)"
    required: false
    default: "microsoft"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  maven-version:
    description: "Maven version to be installed."
    required: true
  working-directory:
    description: "Working directory of your Maven artifacts. (Default is .)"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@1.32.0

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: build

    - name: Set up Maven with version ${{ inputs.maven-version }}
      uses: bakdata/ci-templates/actions/java-maven-setup@feature/maven
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        maven-version: ${{ inputs.maven-version }}

    - name: Create Github release
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/*.jar
