name: "Lint helm chart"
description: "Lint all helm charts in the charts directory of a repository"
inputs:
  ref:
    description: "The ref name to checkout the repository."
    required: false
    default: ${{ github.event.repository.default_branch }}
    type: string
  lint-config-path:
    description: "The path to the lint configuration file (For an example see https://github.com/helm/chart-testing/blob/main/pkg/config/test_config.yaml)."
    required: false
    default: ".github/lint-config.yaml"
    type: string
  helm-version:
    description: "The helm version for setting up poetry."
    required: false
    default: "v3.4.0"
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: "${{ inputs.ref }}"
        # fetch-depth of 2 needed for comparison of helm charts between commits while linting
        fetch-depth: 2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: "${{ inputs.helm-version }}"

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    - name: Run chart-testing (lint)
      run: |
        if [[ "${GITHUB_REF#refs/heads/}" == "main" || "${GITHUB_REF#refs/heads/}" == "master" ]]; then
          ct lint --config ${{ inputs.lint-config-path }} --since HEAD^
        else
          ct lint --config ${{ inputs.lint-config-path }} --since HEAD
        fi
      shell: bash
