name: "Lint Helm chart"
description: "Lint all Helm charts in the charts directory of a repository"
inputs:
  ref:
    description: "The ref name to checkout the repository."
    required: false
    default: ${{ github.ref_name }}
  lint-config-path:
    description: "The path to the lint configuration file (For an example see https://github.com/helm/chart-testing/blob/main/pkg/config/test_config.yaml)."
    required: false
    default: ".github/lint-config.yaml"
  helm-version:
    description: "The Helm version."
    required: false
    default: "v3.10.1"

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout-repo@v1.26.0
      with:
        ref: "${{ inputs.ref }}"
        # fetch-depth of 0 is needed for the comparison of Helm charts from the HEAD of the current
        # branch to the HEAD of the default branch (one or multiple commits in between)
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: "${{ inputs.helm-version }}"

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    # On the default branch we want to lint Helm charts when they have changed compared
    # to the previous commit (HEAD^) and on any other branch we lint Helm charts
    # when there are changes in comparison to the HEAD of the default branch
    # (see --target-branch and --since in https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md)
    - name: Run chart-testing (lint)
      run: |
        if [[ "${GITHUB_REF#refs/heads/}" == "main" || "${GITHUB_REF#refs/heads/}" == "master" ]]; then
          ct lint --config ${{ inputs.lint-config-path }} --since HEAD^
        else
          ct lint --config ${{ inputs.lint-config-path }}
        fi
      shell: bash
