name: "Lint helm chart"
description: "Lint all helm charts in the chart directory"
inputs:
  lint-config-path:
    description: "The path to the lint configuration file (See https://github.com/helm/chart-testing/blob/main/pkg/config/test_config.yaml)."
    required: false
    default: ".github/lint-config.yaml"
    type: string
  helm-version:
    description: "The helm version for setting up poetry."
    required: false
    default: "v3.4.0"
    type: string
runs:
  using: "composite"
  steps:
    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    - name: Run chart-testing (lint)
      run: |
        if [[ "${GITHUB_REF#refs/heads/}" == "main" || "${GITHUB_REF#refs/heads/}" == "master" ]]; then
          ct lint --config ${{ inputs.lint-config-path }} --since HEAD^
        else
          ct lint --config ${{ inputs.lint-config-path }} --since HEAD
        fi
      shell: bash
