name: "Build tarball image"
description: "Build tarball image using Gradle"

inputs:
  image-artifact-name:
    description: "Artifact name to upload tarball image, see https://github.com/actions/upload-artifact"
    required: false
    default: "image-artifact"
  java-distribution:
    description: "Java distribution to be installed. (Default is microsoft)"
    required: false
    default: "microsoft"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  gradle-version:
    description: "Gradle version to be installed. (Default is wrapper)"
    required: false
    default: "wrapper"
  gradle-cache:
    description: "Whether Gradle caching is enabled or not. (Default is true)"
    required: false
    default: true
  working-directory:
    description: "Working directory of your Gradle artifacts. (Default is .)"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Gradle with version ${{ inputs.gradle-version }}
      uses: bakdata/ci-templates/actions/java-gradle-setup@v1.4.0
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        gradle-version: ${{ inputs.gradle-version }}
        gradle-cache: ${{ inputs.gradle-cache }}

    - name: Build Docker image
      run: ./gradlew --info --stacktrace jibBuildTar --image=${{ github.event.repository.name }}:${{ github.run_id }} -x test
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Upload tarball image artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.image-artifact-name }}
        path: build/jib-image.tar
        retention-days: 1
