name: "Build Multi-Platform image"
description: "Build Multi-Platform image using Gradle"

inputs:
  platforms:
    description: "Architectures for the created image (comma separated)"
    required: false
    default: "linux/amd64,linux/arm64"
    type: string
  image-name:
    description: "Name of Docker image."
    required: false
    default: "${{ github.event.repository.name }}"
  additional-tags:
    description: "Addiitional Tags of Jib Image (comma separated list)"
    required: false
    default: ""
  image-tag:
    description: "Tag of Jib Image"
    required: false
    default: "pipeline-${{ github.run_id }}-git-${GITHUB_SHA::8}}"
  full-image-name:
    description: "Full name of image (registry/image:tag) If an image name is provided without a tag, 'latest' will be used. Be careful with registries that dont allow overwriting tags."
    required: true
  allow-insecure-registries:
    description: "Whether to allow insecure registries or not. (Default is false)"
    required: false
    default: "false"
  jib-from-image:
    description: "The Jib base image to use"
    required: false
  class:
    description: "The entrypoint class to be used for the image"
    required: false
  java-distribution:
    description: "Java distribution to be installed. (Default is microsoft)"
    required: false
    default: "microsoft"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  gradle-version:
    description: "Gradle version to be installed. (Default is wrapper)"
    required: false
    default: "wrapper"
  gradle-cache:
    description: "Whether Gradle caching is enabled or not. (Default is true)"
    required: false
    default: "true"
  gradle-cache-read-only:
    description: "Whether Gradle caching should be read-only. By default this value is 'false' for workflows on the GitHub default branch and 'true' for workflows on other branches."
    required: false
    default: ${{ github.event.repository != null && github.ref_name != github.event.repository.default_branch }}
  gradle-refresh-dependencies:
    description: "Whether Gradle should refresh dependencies. (Default is false)"
    required: false
    default: "false"
  working-directory:
    description: "Working directory of your Gradle artifacts. (Default is .)"
    required: false
    default: "."
  download-lfs-files:
    description: "Whether the Git checkout action should resolve LFS files or not. (Default is false)"
    required: false
    default: "false"
  subproject:
    description: "The Gradle subproject for which the image should be built (If not specified, an image for the root project will be built)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@1.32.0
      with:
        lfs: ${{ inputs.download-lfs-files }}

    - name: Set up Gradle with version ${{ inputs.gradle-version }}
      uses: bakdata/ci-templates/actions/java-gradle-setup@1.42.0
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        gradle-version: ${{ inputs.gradle-version }}
        gradle-cache: ${{ inputs.gradle-cache }}
        gradle-cache-read-only: ${{ inputs.gradle-cache-read-only }}

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image-name }}
        tags: |
          event=push,type=raw,value=${{ inputs.additional-tags }}
          event=pr,type=raw,value=${{ inputs.additional-tags }}
          event=tag,type=semver,pattern={{ version }}

    - name: Build Docker image
      run: |
        ./gradlew ${{ inputs.subproject && format('{0}:', inputs.subproject) || '' }}jib \
          --info --stacktrace \
          --image=${{ inputs.image-name }} \
          -Djib.from.platforms=${{ inputs.platforms }} \
          ${{ inputs.jib-from-image && format('-Djib.from.image={0}', inputs.jib-from-image) || '' }} \
          ${{ inputs.class && format('-Djib.container.mainClass={0}', inputs.class) || '' }} \
          -Djib.to.image=${{ inputs.full-image-name }}:${{ inputs.image-tag }} \
          ${{ inputs.gradle-refresh-dependencies == 'true' && '--refresh-dependencies' || '' }} \
          ${{ inputs.allow-insecure-registries == 'true' && '-Djib.allowInsecureRegistries=true' || '' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
