name: "Release Java artifacts"
description: "Release Java Gradle artifacts on Github"

inputs:
  github-token:
    description: "GitHub token for requesting changes from API."
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@1.32.0
      with:
        fetch-depth: 0

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: build

    - name: Generate
      id: build-changelog
      uses: bakdata/ci-templates/actions/changelog-generate@feature/gradle-changelog-action
      with:
        github-token: ${{ inputs.github-token }}
        new-tag: ${{ github.ref_name }}
        fetch-release-information: "true"

    - name: Create Github release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.build-changelog.outputs.single-changelog }}
        files: "**/build/libs/*.jar"
