name: "Release Java artifacts"
description: "Release Java Gradle artifacts on Github"

inputs:
  changelog-file:
    description: Path to the changelog file in the GitHub repository
    required: false
    default: "CHANGELOG.md"
  github-username:
    description: "GitHub username for requesting changes from API."
    required: true
  github-token:
    description: "GitHub token for requesting changes from API."
    required: true
  java-distribution:
    description: "Java distribution to be installed. (Default is microsoft)"
    required: false
    default: "microsoft"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  gradle-version:
    description: "Gradle version to be installed. (Default is wrapper)"
    required: false
    default: "wrapper"
  gradle-cache:
    description: "Whether Gradle caching is enabled or not. (Default is true)"
    required: false
    default: "true"
  working-directory:
    description: "Working directory of your Gradle artifacts. (Default is .)"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@1.32.0

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: build

    - name: Create changelog
      id: build-changelog
      uses: bakdata/ci-templates/actions/changelog-generate@1.35.2
      with:
        github-token: ${{ inputs.github-token }}
        new-tag: ${GITHUB_REF##*/}
        changelog-file: "${{ inputs.changelog-file }}"
        fetch-release-information: "true"

    - name: Create Github release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        files: ./build/**/*.jar
