name: "Release Java artifacts"
description: "Release Java Gradle artifacts on Github"

inputs:
  github-username:
    description: "GitHub username for requesting changes from API."
    required: true
  github-token:
    description: "GitHub token for requesting changes from API."
    required: true
  java-distribution:
    description: "Java distribution to be installed. (Default is microsoft)"
    required: false
    default: "microsoft"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  gradle-version:
    description: "Gradle version to be installed. (Default is wrapper)"
    required: false
    default: "wrapper"
  working-directory:
    description: "Working directory of your Gradle artifacts. (Default is ./)"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: build

    - name: Set up Gradle with version ${{ inputs.gradle-version }}
      uses: bakdata/ci-templates/actions/java-gradle-setup@feature/java-gradle
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        gradle-version: ${{ inputs.gradle-version }}

    - name: Generate changelog
      run: ./gradlew -Pchangelog.releaseVersion=${GITHUB_REF##*/} -Pchangelog.sinceTag=${GITHUB_REF##*/} --stacktrace --info generateChangelog
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_USER: ${{ inputs.github-username }}
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Create Github release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        files: ./build/**/*.jar
