name: "Release Java artifacts"
description: "Release Java Gradle artifacts on Github"

inputs:
  github-token:
    description: "GitHub token for requesting changes from API."
    required: true
  changelog-config-path:
    description: "Path to local git cliff config"
    required: false
    default: "cliff.toml"
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@fix/node-20
      with:
        fetch-depth: 0

    - name: Download build artifact
      uses: actions/download-artifact@v8
      with:
        name: build-artifact
        path: build

    - name: Generate changelog
      id: changelog
      uses: bakdata/ci-templates/actions/changelog-generate@fix/node-20
      with:
        github-token: ${{ inputs.github-token }}
        additional-cliff-args: --current --strip all # passing --tag ${{ github.ref_name }} generates a full changelog
        config-path: ${{ inputs.changelog-config-path }}

    - name: Create Github release
      uses: softprops/action-gh-release@v2.0.4
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        files: "**/build/libs/*.jar"
