name: "Release Java artifacts"
description: "Release Java Gradle artifacts on Github"

inputs:
  changelog-file:
    description: Path to the changelog file in the GitHub repository
    required: false
    default: "CHANGELOG.md"
  github-token:
    description: "GitHub token for requesting changes from API."
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@1.32.0

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: build

    - name: Create changelog
      id: build-changelog
      uses: bakdata/ci-templates/actions/changelog-generate@fix/changelog
      with:
        github-token: ${{ inputs.github-token }}
        new-tag: ${GITHUB_REF##*/}
        changelog-file: ${{ inputs.changelog-file }}
        fetch-release-information: "true"

    - name: Create Github release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        files: "**/build/libs/*.jar"
