name: "Release Java artifacts"
description: "Release Java Gradle artifacts on Github"

inputs:
  github-token:
    description: "GitHub token for requesting changes from API."
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@1.49.0
      with:
        fetch-depth: 0

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: build

    - name: Generate changelog
      uses: bakdata/ci-templates/actions/changelog-generate@1.69.2
      with:
        github-token: ${{ inputs.github-token }}
        tag: ${{ github.ref_name }}

    - name: Create Github release
      uses: softprops/action-gh-release@v2.0.4
      with:
        body: ${{ steps.changelog.outputs.single-changelog }}
        files: "**/build/libs/*.jar"
