name: "Setup poetry"
description: "Install Python and then poetry for a given version"

inputs:
  python-version:
    description: "The python version for setting up poetry."
    required: false
    default: "3.10"
  poetry-version:
    description: "The poetry version to be installed."
    required: false
    default: "1.1.13"
  working-directory:
    description: "The root directory of the poetry project."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install Poetry ${{ inputs.poetry-version }}
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Configure poetry
      run: poetry config virtualenvs.in-project true
      shell: bash

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry
        cache-dependency-path: ${{ inputs.working-directory }}/poetry.lock

    - run: poetry env use ${{ inputs.poetry-version }}
      shell: bash

    - name: Get full Python version
      id: full-python-version
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")
      shell: bash
