name: "Setup poetry"
description: "Set up poetry with virtualenv caching"

inputs:
  python-version:
    description: "The python version for setting up poetry."
    required: false
    default: "3.10"
  poetry-version:
    description: "The poetry version to be installed."
    required: false
    default: "1.2.1"
  working-directory:
    description: "The root directory of the poetry project."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install poetry ${{ inputs.poetry-version }}
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Configure poetry
      run: |
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.path ${{ inputs.working-directory }}/.venv
      shell: bash

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      id: python
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry
        cache-dependency-path: ${{ inputs.working-directory }}/poetry.lock

    - run: poetry env use '${{ steps.python.outputs.python-path }}'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
