name: "Setup Poetry"
description: "Set up Poetry with virtualenv caching"

inputs:
  python-version:
    description: "The Python version for the Poetry virtual environment."
    required: false
    default: "3.10"
  poetry-version:
    description: "The Poetry version to be installed."
    required: false
    default: "1.2.2"
  working-directory:
    description: "The root directory of the Poetry project."
    required: false
    default: "."
  install-pipx:
    description: "Whether to ensure that pipx is installed before invoking it."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install pipx
      if: ${{ inputs.install-pipx == 'true' }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install python3-venv -y
        # Assumes Ubuntu 22.04 or below
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath

    - name: Cache poetry
      id: cache-poetry
      uses: actions/cache@v4
      with:
        path: |
          /opt/pipx/venvs/poetry
          /opt/pipx_bin/poetry
        key: poetry${{ inputs.poetry-version }}-python${{ inputs.python-version }}-${{ runner.os }}

    - name: Install Poetry ${{ inputs.poetry-version }}
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      shell: bash
      run: pipx install poetry==${{ inputs.poetry-version }} --python ${{ steps.setup-python.outputs.python-path }}

    - name: Set up Python ${{ inputs.python-version }} poetry cache
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"
        cache-dependency-path: ${{ inputs.working-directory }}/poetry.lock

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.path ${{ inputs.working-directory }}/.venv
      shell: bash
