name: "Release helm chart"
description: "Release all changed helm charts in this repository"
inputs:
  templatesPath:
    description: "The local path to the root of the ci templates repo."
    default: "./ci-templates"
    required: false
  lintConfig:
    description: "The path to the lint configuration file."
    default: ".github/lint-config.yaml"
    required: false
  releaseType:
    description: "The type of the release."
    default: "patch"
    required: false
  githubToken:
    description: "The personal access token for pushing."
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - name: Lint helm chart
      uses: "${{ inputs.templatesPath }}/helm-lint"
      with:
        lintConfig: ${{ inputs.lintCoinfig }}

    - name: Bump version
      uses: "${{ inputs.templatesPath }}/bump-version"
      with:
        templatesPath: ${{ inputs.templatesPath }}
        githubToken: ${{ inputs.githubToken }}
        releaseType: ${{ inputs.releaseType }}

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.2.1
      env:
        CR_TOKEN: "${{ inputs.githubToken }}"
