name: "Release helm chart"
description: "Release all changed helm charts in this repository"
inputs:
  githubToken:
    description: "The personal access token for pushing."
    required: true
  releaseType:
    description: "The type of the release."
    default: "patch"
    required: false
  lintConfig:
    description: "The path to the lint configuration file."
    default: ".github/lint-config.yaml"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: "v3.4.0"

    - name: Lint helm chart
      uses: ./ci-templates/helm-lint
      with:
        lintConfig: "${{ inputs.lintConfig }}"

    - name: Bump version
      uses: ./ci-templates/bump-version
      with:
        githubToken: "${{ inputs.githubToken }}"
        releaseType: "${{ inputs.releaseType }}"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.2.1
      env:
        CR_TOKEN: "${{ inputs.githubToken }}"
