name: "Release helm chart"
description: "Release all changed helm charts in this repository"
inputs:
  githubToken:
    description: "The personal access token for pushing."
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up git and helm
      uses: ./ci-templates/helm-setup

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.2.1
      env:
        CR_TOKEN: "${{ inputs.githubToken }}"
