name: Port forward Kubernetes service
description: TODO
inputs:
  service:
    description: Name of Kubernetes service
    required: true
  port:
    description: Port to be forwarded
    required: true
  namespace:
    description: Kubernetes namespace
    required: true

runs:
  using: composite
  steps:
    - name: Establish port forward
      shell: bash
      run: |
        nohup kubectl port-forward "services/${{ inputs.service }}" "${{ inputs.port }}:${{ inputs.port }}" --namespace ${{ inputs.namespace }} --kubeconfig $KUBECONFIG > port-forward.out &
        # wait up to 60 seconds for port forwarding
        for i in {1..120}; do if [ "$(cat port-forward.out)" = "Forwarding from 127.0.0.1:${{ inputs.port }} -> ${{ inputs.port }}" ]; then echo "Port forwarding done"; break; else echo "Waiting for port forwarding..."; sleep 0.5; fi; done
