name: Port forward Kubernetes service
description: Creates a port forward for a Kubernetes service and keep it open in the background
inputs:
  namespace:
    description: Kubernetes namespace
    required: true
  port:
    description: Port to be forwarded
    required: true
  service:
    description: Name of Kubernetes service
    required: true
  kubectl-version:
    description: kubectl version, e.g. `v1.23.0` or `latest`
    default: latest
    required: false
  timeout:
    description: Timeout for portfowrd
    default: "30"
    required: false
  kubeconfig:
    description: Path to kubeconfig file
    required: false

runs:
  using: composite
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Establish port forward
      env:
        TIMEOUT: "${{ inputs.timeout }}"
      run: |
        kubectl port-forward "services/${{ inputs.service }}" "${{ inputs.port }}:${{ inputs.port }}" --namespace ${{ inputs.namespace }} ${{ (inputs.kubeconfig != '' && format('--kubeconfig {0}', inputs.kubeconfig)) || '' }} &
        # wait up to $TIMEOUT seconds for port forwarding
        for _ in {1..$TIMEOUT}; do if grep -q "Forwarding from 127.0.0.1:${{ inputs.port }} -> ${{ inputs.port }}" port-forward.out; then
          echo "Port forwarding done"
          break
        else
          cat port-forward.out || true
          echo "Portforwarding failed: Timeout reached"
          exit 1
        fi; done
      shell: bash
