name: "Publish Java artifacts"
description: "Publish Java artifacts using gradle"

inputs:
  signing-secret-key-ring:
    description: "Key ring file for signing the sonatype publication."
    required: true
  signing-key-id:
    description: "Key id for signing the sonatype publication."
    required: true
  signing-password:
    description: "Password for signing the sonatype publication."
    required: true
  ossrh-username:
    description: "Username for signing into sonatype repository."
    required: true
  ossrh-password:
    description: "Password for signing into sonatype repository."
    required: true
  working-directory:
    description: "The working directory of your Gradle artifacts. (Default is root directory)."
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Gradle with version ${{ inputs.gradle-version }}
      uses: bakdata/ci-templates/actions/java-gradle-setup@feature/java-gradle
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        gradle-version: ${{ inputs.gradle-version }}
        gradle-cache: ${{ inputs.gradle-cache }}

    - name: Publish to Nexus
      run: |
        echo '${{ inputs.signing-secret-key-ring }}' | base64 -d > secring.gpg
        if [[ "$GITHUB_REF" =~ ^ref/tags/.* ]]; then
          ./gradlew --info --stacktrace publishToNexus closeAndReleaseRepository -x test
        else
          ./gradlew --info --stacktrace publishToNexus
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SIGNING_SECRET_KEY_RING_FILE: "secring.gpg"
        SIGNING_KEY_ID: "${{ inputs.signing-key-id }}"
        SIGNING_PASSWORD: "${{ inputs.signing-password }}"
        OSSRH_USERNAME: "${{ inputs.ossrh-username }}"
        OSSRH_PASSWORD: "${{ inputs.ossrh-password }}"
        CI: true
    
    - name: Release to Nexus
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo '${{ inputs.signing-secret-key-ring }}' | base64 -d > secring.gpg
        #./gradlew --info --stacktrace closeAndReleaseRepository -x test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SIGNING_SECRET_KEY_RING_FILE: "secring.gpg"
        SIGNING_KEY_ID: "${{ inputs.signing-key-id }}"
        SIGNING_PASSWORD: "${{ inputs.signing-password }}"
        CI: true
