name: "Publish Java artifacts"
description: "Publish Java artifacts using gradle"

inputs:
  github-token:
    description: "The token for github access."
    required: true
  sonar-token:
    description: "The token for sonarcloud."
    required: true
  java-distribution:
    description: "The java distribution to be installed. (Default is temurin)"
    required: false
    default: "temurin"
  java-version:
    description: "The java version to be installed. (Default is 11)"
    required: false
    default: "11"
  gradle-version:
    description: "The gradle version to be installed. (Default is 6.7.1)"
    required: false
    default: "6.7.1"
  gradle-cache:
    description: "The gradle cache to use. Options are gradle, maven, sbt. (Default is gradle)"
    required: false
    default: "gradle"
  integration-tests:
    description: "If true, the action is executing integration tests (Default is true)"
    required: false
    default: true
  docker:
    description: "If true, the action is building a docker image with jib (Default is false)"
    required: false
    default: false
  working-directory:
    description: "The working directory of your Gradle artifacts. (Default is root directory)"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Set up Gradle with version ${{ inputs.gradle-version }}
      uses: bakdata/ci-templates/actions/java-gradle-setup@feature/java-gradle
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        gradle-version: ${{ inputs.gradle-version }}
        gradle-cache: ${{ inputs.gradle-cache }}
