name: "Publish Java artifacts"
description: "Publish Java artifacts using gradle"

inputs:
  signing-secret-key-ring:
    description: "Key ring file for signing the sonatype publication."
    required: true
  signing-key-id:
    description: "Key id for signing the sonatype publication."
    required: true
  signing-password:
    description: "Password for signing the sonatype publication."
    required: true
  ossrh-username:
    description: "Username for signing into sonatype repository."
    required: true
  ossrh-password:
    description: "Password for signing into sonatype repository."
    required: true
  docker-username:
    description: "Username for docker authentication."
    required: false
  docker-password:
    description: "Password for docker authentication."
    required: false
  docker-publisher:
    description: "Publisher to prefix docker image."
    required: false
  working-directory:
    description: "The working directory of your Gradle artifacts. (Default is root directory)."
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Publish to Nexus
      run: |
        echo '${{ inputs.signing-secret-key-ring }}' | base64 -d > secring.gpg
        ./gradlew --info --stacktrace publishToNexus
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SIGNING_SECRET_KEY_RING_FILE: "secring.gpg"
        SIGNING_KEY_ID: "${{ inputs.signing-key-id }}"
        SIGNING_PASSWORD: "${{ inputs.signing-password }}"
        OSSRH_USERNAME: "${{ inputs.ossrh-username }}"
        OSSRH_PASSWORD: "${{ inputs.ossrh-password }}"
        CI: true
    
    - name: Login to DockerHub
      if: ${{ inputs.docker-username != '' && inputs.docker-password != '' && inputs.docker-publisher != '' }}
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Publish docker
      if: ${{ inputs.docker-username != '' && inputs.docker-password != '' && inputs.docker-publisher != '' }}
      run: |
        docker images
        #docker push ${{ inputs.docker-publisher }}/${{ github.event.repository.name }}:${{ github.run_id }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
