name: "Publish Java artifacts"
description: "Publish Java artifacts using gradle"

inputs:
  signing-secret-key-ring:
    description: "The key ring file for signing the sonatype publication."
    required: true
  signing-key-id:
    description: "The key id for signing the sonatype publication."
    required: true
  signing-password:
    description: "The password for signing the sonatype publication."
    required: true
  osshr-username:
    description: "The username for signing into sonatype repository."
    required: true
  osshr-password:
    description: "The password for signing into sonatype repository."
    required: true
  working-directory:
    description: "The working directory of your Gradle artifacts. (Default is root directory)"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Publish to Nexus
      run: |
        echo '${{ inputs.signing-secret-key-ring }}' | base64 -d > secring.gpg
        ./gradlew --info --stacktrace publishToNexus
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SIGNING_SECRET_KEY_RING_FILE: secring.gpg
        SIGNING_KEY_ID: ${{ inputs.signing-key-id }}
        SIGNING_PASSWORD: ${{ inputs.signing-password }}
        OSSRH_USERNAME: ${{ inputs.ossrh-username }}
        OSSRH_PASSWORD: ${{ inputs.ossrh-password }}
        CI: true
