name: "Setup environment"
description: "Setup GKE environment for Kubernetes deployments"
inputs:
  gke-service-account:
    description: "GKE service account key for authentication"
    required: true
  gke-project:
    description: "GKE project id for authentication"
    required: true
  gke-region:
    description: "GKE region for authentication"
    required: true
  gke-cluster:
    description: "GKE cluster for authentication"
    required: true
  python-version:
    description: "Python version"
    default: "3.10"
    required: false
  gcloud-sdk-version:
    description: "GCloud SDK version"
    default: "376.0.0"
    required: false
  kubectl-version:
    description: "Kubectl version"
    default: "v1.23.0"
    required: false
  helm-version:
    description: "Helm version"
    default: "v3.8.1"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}

    - name: Authenticate at GCloud
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ inputs.gke-service-account }}

    - name: Setup GCloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        version: ${{ inputs.gcloud-sdk-version }}
        project_id: ${{ inputs.gke-project }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Setup authentication
      shell: bash
      run: |
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION" --project "$GKE_PROJECT"
      env:
        GKE_REGION: ${{ inputs.gke-region }}
        GKE_CLUSTER: ${{ inputs.gke-cluster }}
        GKE_PROJECT: ${{ inputs.gke-project }}

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: ${{ inputs.helm-version }}
