name: "Kpops runner"
description: "Run Kpops command line with the given params"

inputs:
  mode:
    description: "The command mode you want to use to launch kpops"
    required: true
  pipeline:
    description: "Pipeline file you want to run"
    required: true
  working-directory:
    description: "The root directory containing the config.yaml, pipelines folder and defaults"
    default: "."
  execute:
    description: "Set execution flag"
    default: "false"
  defaults:
    description: "Defaults folder path"
    default: "defaults"
  config:
    description: "config.yaml file path"
    default: "config.yaml"
  components:
    description: "Components package path"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install Kpops
      shell: bash
      run: pip install kpops==0.2.0.dev20221202163038 --extra-index-url https://test.pypi.org/simple/
      
    
    - name: Dry-run ${{ inputs.pipeline }} pipeline
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
         kpops generate ${{ inputs.pipeline }} ${{inputs.components}} --defaults ${{ inputs.defaults }} --config ${{ inputs.config }}
         kpops ${{inputs.mode}} ${{ inputs.pipeline }} ${{inputs.components}}  --defaults ${{ inputs.defaults }} --config ${{ inputs.config }}

    - name: Process ${{ inputs.pipeline }} pipeline
      shell: bash
      working-directory: ${{inputs.working-directory}}
      if: ${{inputs.execute == 'true'}}
      run: kpops ${{inputs.mode}} ${{ inputs.pipeline }} ${{inputs.components}} --defaults ${{ inputs.defaults }} ${{ steps.condval.outputs.value }} --config ${{ inputs.config }} --execute
      
