name: "Build Jib image"
description: "Build Jib image using gradle"

inputs:
  image-artifact-name:
    descritption: "Artifact name to upload jib docker image (see https://github.com/actions/upload-artifact and https://github.com/actions/download-artifact)"
    required: false
    default: "docker-image"
  java-distribution:
    description: "Java distribution to be installed. (Default is temurin)"
    required: false
    default: "temurin"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  gradle-version:
    description: "Gradle version to be installed. (Default is 6.7.1)"
    required: false
    default: "6.7.1"
  gradle-cache:
    description: "Cache to use. Options are gradle, maven, sbt. (Default is '')"
    required: false
    default: ""
  working-directory:
    description: "Working directory of your Gradle artifacts. (Default is root directory)"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Gradle with version ${{ inputs.gradle-version }}
      uses: bakdata/ci-templates/actions/java-gradle-setup@feature/java-gradle
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        gradle-version: ${{ inputs.gradle-version }}
        gradle-cache: ${{ inputs.gradle-cache }}

    - name: Build Docker image
      run: ./gradlew --info --stacktrace jibBuildTar --image=${{ github.event.repository.name }}:${{ github.run_id }} -x test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    
    - name: Upload jib docker image artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ inputs.image-artifact-name }}
        path: build/jib-image.tar
        retention-days: 1
