name: "Bump version"
description: "Bump version with python bump2version using .bumpversion.cfg"

inputs:
  release-type:
    description: "The type of the release (major, minor or patch)."
    required: true
    type: string
  python-version:
    description: "The python version for setting up poetry."
    required: false
    default: "3.10"
    type: string

outputs:
  release-tag:
    description: "The bumped version."
    value: ${{ steps.release-tag.outputs.newTag }}
  old-tag:
    description: "The old version"
    value: ${{ steps.release-tag.outputs.oldTag }}

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Set up bump2version
      run: pip install --no-cache-dir bump2version
      shell: bash

    - name: Bump version
      id: release-tag
      run: bump2version ${{ inputs.release-type }} --no-commit
      shell: bash
