name: "Bump version"
description: "Bump version with python bump-my-version using .bumpversion.toml or .bumpversion.cfg"

inputs:
  release-type:
    description: "The type of the release (major, minor or patch)."
    required: true
  working-directory:
    description: "Directory that contains the bumpversion config (.bumpversion.toml/.bumpversion.cfg) or pyproject.toml."
    required: false
    default: "."
  new-version:
    description: "Optional explicit version to set (overrides release-type)."
    required: false
    default: ""
  allow-dirty:
    description: "Allow unclean Git status in the working directory."
    required: false
    default: "true"

outputs:
  release-version:
    description: "The bumped version of your project."
    value: ${{ steps.bump-version.outputs.new-version }}
  old-version:
    description: "The previous version of your project."
    value: ${{ steps.bump-version.outputs.old-version }}

runs:
  using: "composite"
  steps:
    - name: Set up bump-my-version
      run: |
        pipx install bump-my-version
      shell: bash

    - name: Bump version
      id: bump-version
      run: |
        parameters=(bump --no-commit --no-tag)
        echo "old-version=$(bump-my-version show current_version)" >> "$GITHUB_OUTPUT"
        if [[ "${{ inputs.allow-dirty }}" == "true" ]]; then
          parameters+=(--allow-dirty)
        fi
        if [ -n "${{ inputs.new-version }}" ]; then
          parameters+=(--new-version ${{ inputs.new-version }})
        else
          parameters+=("${{ inputs.release-type }}")
        fi
        bump-my-version "${parameters[@]}"
        echo "new-version=$(bump-my-version show current_version)" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
