name: "Bump version"
description: "Bump version with python bump2version using .bumpversion.cfg"

inputs:
  release-type:
    description: "The type of the release (major, minor or patch)."
    required: true
  working-directory:
    description: "The root directory of the poetry project."
    required: false
    default: "."

outputs:
  release-tag:
    description: "The bumped version."
    value: ${{ steps.release-tag.outputs.newTag }}
  old-tag:
    description: "The old version"
    value: ${{ steps.release-tag.outputs.oldTag }}

runs:
  using: "composite"
  steps:
    - name: Set up bump2version
      run: pipx install --no-cache-dir bump2version
      shell: bash

    - name: Bump version
      id: release-tag
      run: |
        echo ::set-output name=oldTag::$(python -c "from configparser import ConfigParser; cfg = ConfigParser(); cfg.read('.bumpversion.cfg'); print(cfg['bumpversion']['current_version'])")
        bump2version ${{ inputs.release-type }} --no-commit
        echo ::set-output name=newTag::$(python -c "from configparser import ConfigParser; cfg = ConfigParser(); cfg.read('.bumpversion.cfg'); print(cfg['bumpversion']['current_version'])")
      shell: bash
      working-directory: ${{ inputs.working-directory }}
