name: "Build Docker image"
description: "Use a Dockerfile to build an `image.tar` file and upload it to GitHub"

inputs:
  docker-context:
    description: "The docker context."
    required: false
    default: "."
  dockerfile-path:
    description: "Path to the Dockerfile."
    required: false
    default: "Dockerfile"
  image-artifact-name:
    description: "Name of the artifact that contains the Docker image.tar file to push, see https://github.com/actions/upload-artifact (Default is 'image-artifact')."
    required: false
    default: "image-artifact"
  image-name:
    description: "Name of Docker image."
    required: false
    default: "${{ github.event.repository.name }}"
  build-options:
    description: "Extra arguments passed to the `docker build` command."
    required: false
  retention-days:
    description: "Number of days the image artifact should be stored on GitHub."
    required: false
    default: "1"
  working-directory:
    description: "Working directory for your Docker artifacts."
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Build Dockerfile and store them in "${{ runner.temp }}/docker-build" directory
      run: |
        docker build -t ${{ inputs.image-name }} -f ${{ inputs.dockerfile-path }} ${{ inputs.docker-context }} ${{ inputs.build-options }}
        mkdir ${{ runner.temp }}/docker-build
        docker save ${{ inputs.image-name }} > ${{ runner.temp }}/docker-build/${{ inputs.image-name }}.tar
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Upload Docker image tar artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: ${{ inputs.image-artifact-name }}
        path: ${{ runner.temp }}/docker-build
        retention-days: ${{ inputs.retention-days }}
