name: "Build Docker image"
description: "Use a Dockerfile to build an image and optionally upload it as a GitHub artifact." 

inputs:
  docker-context:
    description: "The docker context."
    required: false
    default: "."
  dockerfile-path:
    description: "Path to the Dockerfile."
    required: false
    default: "Dockerfile"
  image-name:
    description: "Name of Docker image."
    required: false
    default: "${{ github.event.repository.name }}"
  image-artifact-name:
    description: "Optionally upload an image.tar file as a GitHub artifact by setting an artifact name, see https://github.com/actions/upload-artifact (Default is empty, so not uploading)."
    required: false
    default: ""
  retention-days:
    description: "Number of days the image artifact should be stored on GitHub."
    required: false
    default: "1"
  working-directory:
    description: "Working directory for your Docker artifacts."
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Build 
      run: docker build -t "${{ inputs.image-name }}" -f "${{ inputs.dockerfile-path }}" "${{ inputs.docker-context }}"
      shell: bash
      working-directory: "${{ inputs.working-directory }}"

    - name: Save image 
      if: ${{ inputs.image-artifact-name != '' }} 
      run: |
        mkdir "${{ runner.temp }}/docker-build"
        docker save "${{ inputs.image-name }}" > "${{ runner.temp }}/docker-build/${{ inputs.image-name }}.tar"
      shell: bash
      working-directory: "${{ inputs.working-directory }}"

    - name: Upload image artifact
      if: ${{ inputs.image-artifact-name != '' }} 
      uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.image-artifact-name }}"
        path: "${{ runner.temp }}/docker-build"
        retention-days: "${{ inputs.retention-days }}"

