name: "Build Docker image"
description: "Use a Dockerfile to build an `image.tar` file and upload it to GitHub"

inputs:
  docker-context:
    description: "The docker context."
    required: false
    default: "."
  dockerfile-path:
    description: "Path to the Dockerfile."
    required: false
    default: "Dockerfile"
  image-artifact-name:
    description: "Name of the artifact that contains the Docker image.tar file to push, see https://github.com/actions/upload-artifact (Default is 'image-artifact')."
    required: false
    default: "image-artifact"
  image-name:
    description: "Name of Docker image (Default is the repository name)."
    required: false
    default: "${{ github.event.repository.name }}"
  retention-days:
    description: "Number of days the image artifact should be stored on GitHub."
    required: false
    default: 1
runs:
  using: "composite"
  steps:
    - name: Build Dockerfile and store them in "build" directory
      run: |
        docker build -t ${{ inputs.image-name }}:${{ github.run_id }} -f ${{ inputs.dockerfile-path }} ${{ inputs.docker-context }}
        mkdir build
        docker save ${{ inputs.image-name }}:${{ github.run_id }} > build/${{ inputs.image-name }}.tar
      shell: bash

    - name: Upload Docker image tar artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: ${{ inputs.image-artifact-name }}
        path: build
        retention-days: ${{ inputs.retention-days }}
