name: "Build Java artifacts"
description: "Build Java artifacts using Maven"

inputs:
  maven-version:
    description: "Maven version to be installed."
    required: true
  java-distribution:
    description: "Java distribution to be installed. (Default is microsoft)"
    required: false
    default: "microsoft"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  working-directory:
    description: "Working directory of your Maven artifacts. (Default is .)"
    required: false
    default: "."
  command:
    description: "Command to run build with. (Default is compile)"
    required: false
    default: "compile"
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@1.32.0

    - name: Set up Maven with version ${{ inputs.maven-version }}
      uses: bakdata/ci-templates/actions/java-maven-setup@1.46.8
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        maven-version: ${{ inputs.maven-version }}

    - name: Compile
      run: mvn clean ${{ inputs.command }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
