name: "Build Java artifacts"
description: "Build Java artifacts using Gradle"
inputs:
  build-artifact-name:
    description: "Artifact name that is used for uploading build artifacts, see https://github.com/actions/upload-artifact (Default is build-artifact)."
    required: false
    default: "build-artifact"
  java-distribution:
    description: "Java distribution to be installed. (Default is microsoft)"
    required: false
    default: "microsoft"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  gradle-version:
    description: "Gradle version to be installed. (Default is wrapper)"
    required: false
    default: "wrapper"
  gradle-cache:
    description: "Whether Gradle caching is enabled or not. (Default is true)"
    required: false
    default: "true"
  gradle-cache-read-only:
    description: "Whether Gradle caching should be read-only. By default this value is 'false' for workflows on the GitHub default branch and 'true' for workflows on other branches."
    required: false
    default: ${{ github.event.repository != null && github.ref_name != github.event.repository.default_branch }}
  gradle-refresh-dependencies:
    description: "Whether Gradle should refresh dependencies. (Default is false)"
    required: false
    default: "false"
  gradle-dependency-graph:
    description: "Configure GitHub dependency graph for Gradle. See https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#github-dependency-graph-support. (Default is disabled)"
    required: false
    default: "disabled"
  working-directory:
    description: "Working directory of your Gradle artifacts. (Default is .)"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: bakdata/ci-templates/actions/checkout@1.49.0
    - name: Set up Gradle with version ${{ inputs.gradle-version }}
      uses: bakdata/ci-templates/actions/java-gradle-setup@1.63.0
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        gradle-version: ${{ inputs.gradle-version }}
        gradle-cache: ${{ inputs.gradle-cache }}
        gradle-cache-read-only: ${{ inputs.gradle-cache-read-only }}
        gradle-dependency-graph: ${{ inputs.gradle-dependency-graph }}
    - name: Compile
      run: ./gradlew --info --stacktrace build -x test ${{ inputs.gradle-refresh-dependencies == 'true' && '--refresh-dependencies' || '' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Build jar
      run: ./gradlew --info --stacktrace jar
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.build-artifact-name }}
        path: ${{ inputs.working-directory }}/**/build/libs/*.jar
        retention-days: 1
