name: "Build Java artifacts"
description: "Build Java artifacts using gradle"

inputs:
  sonar-token:
    description: "The token for sonarcloud."
    required: true
  signing-secret-key-ring:
    description: "The key ring file for signing the sonatype publication."
    required: true
  signing-key-id:
    description: "The key id for signing the sonatype publication."
    required: true
  signing-password:
    description: "The password for signing the sonatype publication."
    required: true
  integration-tests:
    description: "If true, the action is executing integration tests (Default is true)"
    required: false
    default: true
  docker:
    description: "If true, the action is building a docker image with jib (Default is false)"
    required: false
    default: false
  shell:
    description: "Shell to use for run steps. (Default is bash)"
    required: false
    default: "bash"
  working-directory:
    description: "Working directory of your Gradle artifacts. (Default is root directory)"
    required: false
    default: "./"
runs:
  using: "composite"
  defaults:
    run:
      shell: ${{ inputs.shell }}
      working-directory: ${{ inputs.working-directory }}
  steps:
    ### Build

    - name: Compile
      run: ./gradlew --info --stacktrace assemble
    
    ### Test

    - name: Run unit tests
      run: ./gradlew check --info --stacktrace -PexcludeTests="**/*IntegrationTest*"
    
    - name: Run integration tests
      if: ${{ inputs.integration-tests == 'true' }}
      run: ./gradlew check --info --stacktrace -PincludeTests="**/*IntegrationTest*"
    
    # sonar.branch.autoconfig.disabled is necessary for autocreation of projects on sonarcloud to work
    - name: Assess code quality
      run: ./gradlew -Dsonar.branch.autoconfig.disabled=true -Dsonar.projectKey=github-playground -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=bakdata --info --stacktrace sonarqube
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}

    - name: Check if everything builds (incl. javadoc) for snapshot/release and signing works
      run: |
        echo '${{ inputs.signing-secret-key-ring }}' | base64 -d > secring.gpg
        ./gradlew --info --stacktrace signSonatypePublication
      env:
        SIGNING_SECRET_KEY_RING_FILE: secring.gpg
        SIGNING_KEY_ID: ${{ inputs.signing-key-id }}
        SIGNING_PASSWORD: ${{ inputs.signing-password }}
        CI: true

    ### Build and upload docker image

    - name: Build Docker image
      if: ${{ inputs.docker == 'true' }}
      run: ./gradlew --info --stacktrace jibBuildTar --image=${{ github.event.repository.name }}:${{ github.run_id }} -x test
    
    - name: Upload Docker image
      if: ${{ inputs.docker == 'true' }}
      uses: actions/upload-artifact@master
      with:
        name: docker-image
        path: /build/jib-image.tar
