name: "Build Java artifacts"
description: "Build Java artifacts using gradle"

inputs:
  sonar-token:
    description: "The token for sonarcloud."
    required: true
  signing-secret-key-ring:
    description: "The key ring file for signing the sonatype publication."
    required: true
  signing-key-id:
    description: "The key id for signing the sonatype publication."
    required: true
  signing-password:
    description: "The password for signing the sonatype publication."
    required: true
  integration-tests:
    description: "If true, the action is executing integration tests (Default is true)"
    required: false
    default: true
  docker:
    description: "If true, the action is building a docker image with jib (Default is false)"
    required: false
    default: false
  working-directory:
    description: "The working directory of your Gradle artifacts. (Default is root directory)"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Compile
      run: ./gradlew --info --stacktrace assemble
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    
    - name: Run unit tests
      run: ./gradlew check --info --stacktrace -PexcludeTests="**/*IntegrationTest*"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    
    - name: Run integration tests
      if: ${{ inputs.integration-tests  == 'true' }}
      run: ./gradlew check --info --stacktrace -PincludeTests="**/*IntegrationTest*"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    
    - name: Build Docker image
      if: ${{ inputs.docker  == 'true' }}
      run: ./gradlew --info --stacktrace jibBuildTar --image=${{ github.event.repository.name }}:${{ github.run_id }} -x test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    
    # sonar.branch.autoconfig.disabled is necessary for autocreation of projects on sonarcloud to work
    - name: Assess code quality
      run: ./gradlew -Dsonar.branch.autoconfig.disabled=true -Dsonar.projectKey=github-playground -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=bakdata --info --stacktrace sonarqube
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}

    - name: Prepare sonatype environment
      run: echo '${{ inputs.signing-secret-key-ring }}' | base64 -d > secring.gpg
      shell: bash

    - name: Check if everything builds (incl. javadoc) for snapshot/release and signing works
      run: ./gradlew --info --stacktrace signSonatypePublication
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        SIGNING_SECRET_KEY_RING_FILE: secring.gpg
        SIGNING_KEY_ID: ${{ inputs.signing-key-id }}
        SIGNING_PASSWORD: ${{ inputs.signing-password }}
