name: "Build Java artifacts"
description: "Build Java artifacts using gradle"

inputs:
  build-artifact-name:
    description: "Pipeline artifact name that is used for uploading build artifacts, see https://github.com/actions/upload-artifact."
    required: false
    default: "build-artifact"
  java-distribution:
    description: "Java distribution to be installed. (Default is microsoft)"
    required: false
    default: "microsoft"
  java-version:
    description: "Java version to be installed. (Default is 11)"
    required: false
    default: "11"
  gradle-version:
    description: "Gradle version to be installed. (Default is wrapper)"
    required: false
    default: "wrapper"
  working-directory:
    description: "Working directory of your Gradle artifacts. (Default is root directory)"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Gradle with version ${{ inputs.gradle-version }}
      uses: bakdata/ci-templates/actions/java-gradle-setup@feature/java-gradle
      with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        gradle-version: ${{ inputs.gradle-version }}
    
    - name: Compile
      run: ./gradlew --info --stacktrace build -x test
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Build jar
      run: ./gradlew --info --stacktrace jar
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.build-artifact-name }}
        path: ./**/build/libs/*.jar
        retention-days: 1
