name: "Deploy helm chart"
description: "Deploy a helm chart to the GKE cluster"
inputs:
  release-name:
    description: "Helm release name"
    required: true
  namespace:
    description: "K8s namespace to deploy in"
    required: true
  chart:
    description: "Helm chart to deploy"
    required: true
  chart-version:
    description: "Chart Version"
    required: true
  values-yaml:
    description: "File path as string for a single helm value file or as json array for multiple helm value files."
    required: true
  repository-name:
    description: "Helm repository name"
    required: false
  repository-url:
    description: "Url of the repository"
    required: false
runs:
  using: "composite"
  steps:
    - name: Add helm repository
      shell: bash
      run: |
        if [ -n "$REPOSITORY_NAME" ] && [ -n "$REPOSITORY_URL" ]
        then
          helm repo add "$REPOSITORY_NAME" "$REPOSITORY_URL"
          helm repo update
        else
          echo "No repository specified; Skipping step"
        fi
      env:
        REPOSITORY_NAME: ${{ inputs.repository-name }}
        REPOSITORY_URL: ${{ inputs.repository-url }}

    - name: Deploy helm chart
      shell: bash
      run: |
        if $(echo '${{ inputs.values-yaml }}' | jq -e > /dev/null 2>&1); then
          echo "Deploying with multiple value files"
          helm upgrade --debug --install --wait --timeout 1200s --force \
            --version ${{ inputs.chart-version }} \
            $(echo '${{ inputs.values-yaml }}' | jq -r '[ .[] | . = "--values \(.)"] | join(" ")') \
            --namespace ${{ inputs.namespace }} \
            ${{ inputs.release-name }} ${{ inputs.chart }}
        else
          echo "Deploying with single value file"
          helm upgrade --debug --install --wait --timeout 1200s --force \
            --version ${{ inputs.chart-version }} \
            --values ${{ inputs.values-yaml }} \
            --namespace ${{ inputs.namespace }} \
            ${{ inputs.release-name }} ${{ inputs.chart }}
        fi
