name: "Publish Python package PyPI"
description: "Publish Python packages using Poetry to TestPyPI or PyPI"

inputs:
  pypi-token:
    description: "The PyPI token for publishing packages."
    required: true
  publish-to-test:
    description: "If set to false, the packages are published to PyPI. (Default is true)"
    required: false
    default: "true"
  working-directory:
    description: "The working directory of your Python packages. (Default is root directory)"
    required: false
    default: "./"

runs:
  using: "composite"
  steps:
    - name: Build package
      run: poetry build
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Publish package to PyPI
      if: ${{ inputs.publish-to-test == 'false' }}
      run: |
        # If the repository is not specified, by default Poetry pushes the packages to PyPI
        poetry publish --username __token__ --password ${{ inputs.pypi-token }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Build and Publish package to TestPyPI
      if: ${{ inputs.publish-to-test == 'true' }}
      run: |
        # set the repository to TestPyPI
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        # first build the project then publish to TestPyPI
        poetry publish --repository testpypi --username __token__ --password ${{ inputs.pypi-token }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
