name: "Tag and release"
description: "Tag and release your repo with target tag."

inputs:
  tag:
    description: "The version of the tag to be publish and released e.g 1.0.0"
    required: true
  release-title:
    description: "Text for the github release title"
    required: true
  release-body:
    description: "Text for the github release body (this describes the release content / Changelog)"
    default: ""
    required: false

runs:
  using: "composite"
  steps:

    - name: Create tag
      run: |
        git config --local user.name ${{ secrets.GH_USERNAME }}
        git config --local user.email ${{ secrets.GH_EMAIL }}
        git tag v${{ inputs.tag }}
      shell: bash

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: "${{ inputs.tag }}"
        name: ${{ inputs.release-title }}
        body: ${{ inputs.release-body }}
        draft: false
        prerelease: false
