name: "Tag and release"
description: "Tag and release with target tag."

inputs:
  tag:
    description: "The version of the tag to be publish and released, e.g. 1.0.0"
    required: true
  release-title:
    description: "Text for the GitHub release title"
    required: true
  release-body:
    description: "Text for the GitHub release body (this describes the release content / Changelog)"
    default: ""
    required: false
  github-username:
    description: "The GitHub username for committing the changes."
    required: true
  github-email:
    description: "The GitHub email for committing the changes."
    required: true
  github-token:
    description: "The GitHub token for committing the changes."
    required: true

runs:
  using: "composite"
  steps:
    - name: Create tag
      run: |
        git config --local user.name ${{ inputs.github-username }}
        git config --local user.email ${{ inputs.github-username }}
        git tag v${{ inputs.tag }}
      shell: bash

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        tag_name: "${{ inputs.tag }}"
        name: ${{ inputs.release-title }}
        body: ${{ inputs.release-body }}
        draft: false
        prerelease: false
