name: "Docker Build and Publish"
description: "Use a Dockerfile to build and publish an image"

inputs:
  docker-context:
    description: "The docker context."
    required: false
    default: "."
  dockerfile-path:
    description: "Path to the Dockerfile."
    required: false
    default: "Dockerfile"
  image-name:
    description: "Name of Docker image."
    required: false
    default: "${{ github.event.repository.name }}"
  working-directory:
    description: "Working directory for your Docker artifacts."
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    # setup-buildx action will create and boot a builder using by default the docker-container driver.
    # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Build
      uses: bakdata/ci-templates/actions/docker-build@feat/docker-optional-artifact
      with:
        docker-context: "${{ inputs.docker-context }}"
        dockerfile-path: "${{ inputs.dockerfile-path }}"
        image-name: "${{ inputs.image-name }}"
        working-directory: "${{ inputs.working-directory }}"

    - name: Publish
      uses: bakdata/ci-templates/actions/docker-push@feat/docker-optional-artifact
      with:
        docker-registry: "${{ inputs.docker-registry }}"
        image-namespace: "${{ inputs.image-namespace }}"
        image-name: "${{ inputs.image-name }}"
        image-tag: "${{ inputs.image-tag }}"
        working-directory: "${{ inputs.working-directory }}"

