name: Format

on:
  pull_request:

jobs:
  format:
    name: dprint
    runs-on: ubuntu-latest
    steps:
      - uses: bakdata/ci-templates/actions/checkout@1.32.0

      - name: Check formatting
        uses: dprint/check@v2.1
