name: Lint

on:
  pull_request:

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Lint actions and workflows
        uses: bakdata/ci-templates/actions/action-lint@1.78.0
        with:
          action-lint-version: "v1.7.11"
