name: Pre-Commit Check

on:
  pull_request:

jobs:
  pre-commit-check:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installation
        run: |
          brew install pre-commit
          brew install tj-actions/tap/auto-doc
        working-directory: .

      - name: Run pre-commit
        run: |
          pre-commit run
        working-directory: .
