name: Pre-Commit Check

on:
  pull_request:

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Installation
        run: |
          pip install pre-commit
          go install github.com/tj-actions/auto-doc@latest
        working-directory: .

      - name: Run pre-commit
        run: |
          echo "=================-================="
          auto-doc
          echo "=================-================="
          # go install github.com/tj-actions/auto-doc@v3
          # pre-commit install
          pre-commit run --all-files
        working-directory: .
