name: Pre-Commit Check

on:
  pull_request:

jobs:
  pre-commit-check:
    # runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installation
        run: |
          # pip install --upgrade pip
          # pip install pre-commit
          # go install github.com/tj-actions/auto-doc@latest
          brew install pre-commit
          brew install tj-actions/tap/auto-doc
        working-directory: .

      - name: Run pre-commit
        run: |
          echo "=================-================="
          auto-doc -h
          echo "=================-================="
          pre-commit run
        working-directory: .
