name: Release
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Scope of the release.
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major
jobs:
  release:
    name: Release
    uses: bakdata/ci-templates/.github/workflows/bump-version-release.yaml@tiedemann/use-gsm-secerts-in-workflow-calls
    with:
      release-type: ${{ github.event.inputs.release-type }}
    secrets:
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
permissions:
  contents: read
  id-token: write
