name: Test python-setup-poetry action
on:
  pull_request:
    branches:
      - main
    paths:
      - actions/parse-secret-definitions
jobs:
  tests:
    name: Python action unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: bakdata/ci-templates/actions/checkout@1.32.0
      - name: setup python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12"
      - name: Run all tests
        run: |
          find . -name "tests.py" -print0 | xargs -0i python -m unittest
