name: Format

on:
  pull_request:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check formatting
        uses: dprint/check@v2.1
