name: Reusable workflow for linting helm charts

on:
  workflow_call:
    inputs:
      ref:
        description: "The ref name to checkout the repository."
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
      chart-directory:
        description: "The parent directory of all charts in this repository."
        default: "charts"
        required: false
        type: string
      lint-config-path:
        description: "The path to the lint configuration file (See https://github.com/helm/chart-testing/blob/main/pkg/config/test_config.yaml)."
        required: false
        default: ".github/lint-config.yaml"
        type: string
      helm-version:
        description: "The helm version for setting up poetry."
        required: false
        default: "v3.4.0"
        type: string

jobs:
  create-release:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
          # fetch-depth: 0
          # persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "${{ inputs.helm-version }}"

      - name: Lint helm chart
        uses: bakdata/ci-templates/actions/helm-lint@main
        with:
          lintConfig: "${{ inputs.lint-config-path }}"
