name: Helm GKE Deploy
# Reusable workflow for deploying a Helm chart on GKE Kubernetes

on:
  workflow_call:
    inputs:
      release-name:
        description: "Helm release name"
        required: true
        type: string
      namespace:
        description: "K8s namespace to deploy in"
        required: true
        type: string
      chart:
        description: "Helm chart to deploy"
        required: true
        type: string
      values-yaml:
        description: "File path as string for a single Helm value file or as json array for multiple Helm value files"
        required: true
        type: string
      repository-name:
        description: "Helm repository name"
        required: false
        type: string
      repository-url:
        description: "Url of the repository"
        required: false
        type: string
      chart-version:
        description: "Chart version"
        required: false
        type: string
      post-renderer:
        description: "File path as string for a Helm post renderer"
        required: false
        type: string
      timeout:
        description: "Timeout for the Helm command in seconds"
        default: "1200"
        required: false
        type: string
      gcloud-sdk-version:
        description: "GCloud SDK version"
        default: "376.0.0"
        required: false
        type: string
      kubectl-version:
        description: "Kubectl version"
        default: "v1.23.0"
        required: false
        type: string
      helm-version:
        description: "Helm version"
        default: "v3.8.1"
        required: false
        type: string
    secrets:
      gke-service-account:
        description: "GKE service account key for authentication"
        required: true
      gke-project:
        description: "GKE project id for authentication"
        required: true
      gke-region:
        description: "GKE region for authentication"
        required: true
      gke-cluster:
        description: "GKE cluster for authentication"
        required: true

jobs:
  helm-deploy:
    name: Helm Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup credentials
        uses: bakdata/ci-templates/actions/setup-credentials@v1.20.0
        with:
          gke-service-account: ${{ secrets.gke-service-account }}
          gke-project: ${{ secrets.gke-project }}
          gke-region: ${{ secrets.gke-region }}
          gke-cluster: ${{ secrets.gke-cluster }}
          gcloud-sdk-version: ${{ inputs.gcloud-sdk-version }}

      - name: Setup environment
        uses: bakdata/ci-templates/actions/helm-setup@v1.20.0
        with:
          kubectl-version: ${{ inputs.kubectl-version }}
          helm-version: ${{ inputs.helm-version }}

      - name: Deploy Helm chart
        uses: bakdata/ci-templates/actions/helm-deploy@v1.20.0
        with:
          release-name: ${{ inputs.release-name }}
          namespace: ${{ inputs.namespace }}
          chart: ${{ inputs.chart }}
          values-yaml: ${{ inputs.values-yaml }}
          chart-version: ${{ inputs.chart-version }}
          post-renderer: ${{ inputs.post-renderer }}
          timeout: ${{ inputs.timeout }}
          repository-name: ${{ inputs.repository-name }}
          repository-url: ${{ inputs.repository-url }}
