name: Helm lint
# Reusable workflow to lint Helm charts

on:
  workflow_call:
    inputs:
      ref:
        description: "The ref name to checkout the repository."
        required: false
        default: ${{ github.ref_name }}
      lint-config-path:
        description: "The path to the lint configuration file (For an example see https://github.com/helm/chart-testing/blob/main/pkg/config/test_config.yaml)."
        required: false
        default: ".github/lint-config.yaml"
      helm-version:
        description: "The Helm version."
        required: false
        default: "v3.10.1"
      check-version-increment:
        description: "Activates a check for chart version increments."
        required: false
        default: "true"

jobs:
  helm-lint:
    name: Helm Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Lint Helm chart
        uses: bakdata/ci-templates/actions/helm-lint@feat/lint-default-action
        with:
          lint-config-path: "${{ inputs.lint-config-path }}"
          ref: "${{ inputs.ref }}"
          check-version-increment: "${{ inputs.check-version-increment }}"
          helm-version: "${{ inputs.helm-version }}"
