name: Java Gradle Docker
# Reusable workflow for building and publishing Java Gradle artifacts including a tarball image

on:
  workflow_call:
    inputs:
      docker-publisher:
        description: "Publisher to prefix Docker image."
        required: true
        type: string
      java-distribution:
        description: "Java distribution to be installed. (Default is microsoft)"
        required: false
        type: string
        default: "microsoft"
      java-version:
        description: "Java version to be installed. (Default is 11)"
        required: false
        type: string
        default: "11"
      gradle-version:
        description: "Gradle version to be installed. (Default is wrapper)"
        required: false
        type: string
        default: "wrapper"
      gradle-cache:
        description: "Whether Gradle caching is enabled or not. (Default is true)"
        required: false
        type: boolean
        default: true
      working-directory:
        description: "Working directory of your Gradle artifacts. (Default is .)"
        required: false
        type: string
        default: "."
    secrets:
      sonar-token:
        description: "Token for Sonarcloud."
        required: true
      sonar-organization:
        description: "Organization for Sonarcloud"
        required: true
      signing-secret-key-ring:
        description: "Key ring (base64 encoded) for signing the Sonatype publication."
        required: true
      signing-key-id:
        description: "Key id for signing the Sonatype publication."
        required: true
      signing-password:
        description: "Password for signing the Sonatype publication."
        required: true
      ossrh-username:
        description: "Username for signing into Sonatype repository."
        required: true
      ossrh-password:
        description: "Password for signing into Sonatype repository."
        required: true
      docker-username:
        description: "Username for publishing to Dockerhub."
        required: true
      docker-password:
        description: "Password for publishing to Dockerhub."
        required: true
      github-username:
        description: "GitHub username for requesting changes from API."
        required: true
      github-token:
        description: "GitHub token for requesting changes from API."
        required: true

jobs:
  java-gradle-base:
    name: Build, Test and Assess code quality
    runs-on: ubuntu-22.04

    steps:
      - name: Build, Test & Assess
        uses: bakdata/ci-templates/actions/java-gradle-base@feat/split-test
        # uses: bakdata/ci-templates/actions/java-gradle-base@1.35.0

        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}
          signing-key-id: ${{ secrets.signing-key-id }}
          signing-password: ${{ secrets.signing-password }}
          signing-secret-key-ring: ${{ secrets.signing-secret-key-ring }}
          sonar-organization: ${{ secrets.sonar-organization }}
          sonar-token: ${{ secrets.sonar-token }}

  build-jib:
    name: Build tarball image
    runs-on: ubuntu-22.04
    needs: java-gradle-base

    steps:
      - name: Build tarball image
        uses: bakdata/ci-templates/actions/java-gradle-build-jib@v1.16.0
        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}

  publish:
    name: Publish
    runs-on: ubuntu-22.04
    needs: build-jib

    steps:
      - name: Publish
        uses: bakdata/ci-templates/actions/java-gradle-publish@v1.16.0
        with:
          signing-secret-key-ring: ${{ secrets.signing-secret-key-ring }}
          signing-key-id: ${{ secrets.signing-key-id }}
          signing-password: ${{ secrets.signing-password }}
          ossrh-username: ${{ secrets.ossrh-username }}
          ossrh-password: ${{ secrets.ossrh-password }}
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}

  publish-jib-image:
    name: Publish tarball image
    runs-on: ubuntu-22.04
    needs: build-jib

    steps:
      - name: Publish tarball image
        uses: bakdata/ci-templates/actions/docker-publish@v1.16.0
        with:
          publisher: ${{ inputs.docker-publisher }}
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}

  release:
    name: Create Github release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: publish

    steps:
      - name: Release on Github
        uses: bakdata/ci-templates/actions/java-gradle-release-github@v1.16.0
        with:
          github-username: ${{ secrets.github-username }}
          github-token: ${{ secrets.github-token }}
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}
