name: Java Gradle library
description: Reusable workflow for building and publishing Java gradle libraries

on:
  workflow_call:
    inputs:
      java-distribution:
        description: "Java distribution to be installed. (Default is microsoft)"
        required: false
        type: string
        default: "microsoft"
      java-version:
        description: "Java version to be installed. (Default is 11)"
        required: false
        type: string
        default: "11"
      gradle-version:
        description: "Gradle version to be installed. (Default is wrapper)"
        required: false
        type: string
        default: "wrapper"
      working-directory:
        description: "Working directory of your Gradle artifacts. (Default is root directory)"
        required: false
        type: string
        default: "./"
    secrets:
      sonar-token:
        description: "Token for Sonarcloud."
        required: true
      signing-secret-key-ring:
        description: "Key ring file for signing the sonatype publication."
        required: true
      signing-key-id:
        description: "Key id for signing the sonatype publication."
        required: true
      signing-password:
        description: "Password for signing the sonatype publication."
        required: true
      ossrh-username:
        description: "Username for signing into sonatype repository."
        required: true
      ossrh-password:
        description: "Password for signing into sonatype repository."
        required: true
      gradle-publish-key:
        description: "Key for publishing to gradle plugin portal."
        required: true
      gradle-publish-secret:
        description: "Secret for publishing to gradle plugin portal."
        required: true
      github-username:
        description: "GitHub username for requesting changes from API."
        required: true
      github-token:
        description: "GitHub token for requesting changes from API."
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        uses: bakdata/ci-templates/actions/java-gradle-build@feature/java-gradle
        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          working-directory: ${{ inputs.working-directory }}

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Test
        uses: bakdata/ci-templates/actions/java-gradle-test@feature/java-gradle
        with:
          sonar-token: ${{ secrets.sonar-token }}
          signing-secret-key-ring: ${{ secrets.signing-secret-key-ring }}
          signing-key-id: ${{ secrets.signing-key-id }}
          signing-password: ${{ secrets.signing-password }}   
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          working-directory: ${{ inputs.working-directory }}

  publish:
    name: Publish
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Publish
        uses: bakdata/ci-templates/actions/java-gradle-publish@feature/java-gradle
        with:
          signing-secret-key-ring: ${{ secrets.signing-secret-key-ring }}
          signing-key-id: ${{ secrets.signing-key-id }}
          signing-password: ${{ secrets.signing-password }}
          ossrh-username: ${{ secrets.ossrh-username }}
          ossrh-password: ${{ secrets.ossrh-password }}
          gradle-publish-key: ${{ secrets.gradle-publish-key }}
          gradle-publish-secret: ${{ secrets.gradle-publish-secret }}
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          working-directory: ${{ inputs.working-directory }}
  
  release:
    name: Create Github release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: publish
  
    steps:
      - name: Release on Github
        uses: bakdata/ci-templates/actions/java-gradle-github-release@feature/java-gradle
        with:
          github-username: ${{ secrets.github-username }}
          github-token: ${{ secrets.github-token }}
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          working-directory: ${{ inputs.working-directory }}
