name: Java Gradle Release
# Reusable workflow for releasing Java Gradle projects

on:
  workflow_call:
    inputs:
      release-type:
        description: "Scope of the release (major, minor or patch)."
        required: true
        type: string
      java-distribution:
        description: "Java distribution to be installed. (Default is microsoft)"
        required: false
        type: string
        default: "microsoft"
      java-version:
        description: "Java version to be installed. (Default is 11)"
        required: false
        type: string
        default: "11"
      gradle-version:
        description: "Gradle version to be installed. (Default is wrapper)"
        required: false
        type: string
        default: "wrapper"
      gradle-cache:
        description: "Whether Gradle caching is enabled or not. (Default is true)"
        required: false
        type: boolean
        default: true
      working-directory:
        description: "Working directory of your Gradle artifacts. (Default is .)"
        required: false
        type: string
        default: "."
    secrets:
      github-username:
        description: "GitHub username for committing the changes."
        required: true
      github-email:
        description: "GitHub email for committing the changes."
        required: true
      github-token:
        description: "GitHub token for committing the changes."
        required: true

    # Map the workflow outputs to job outputs
    outputs:
      release-version:
        description: "Bumped version of your project."
        value: ${{ jobs.release.outputs.release-version }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    # Map the job outputs to step outputs
    outputs:
      release-version: ${{ steps.release.outputs.release-version }}

    steps:
      - name: Release on Github
        id: release
        uses: bakdata/ci-templates/actions/java-gradle-release@v1.17.0
        with:
          release-type: ${{ inputs.release-type }}
          github-email: ${{ secrets.github-email }}
          github-username: ${{ secrets.github-username }}
          github-token: ${{ secrets.github-token }}
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}
