name: Reusable workflow for building and publishing java gradle artifacts

on:
  workflow_call:
    inputs:
      java-distribution:
        description: "The java distribution to be installed. (Default is temurin)"
        required: false
        type: string
        default: "temurin"
      java-version:
        description: "The java version to be installed. (Default is 11)"
        required: false
        type: string
        default: "11"
      gradle-version:
        description: "The gradle version to be installed. (Default is 6.7.1)"
        required: false
        type: string
        default: "6.7.1"
      gradle-cache:
        description: "The gradle cache to use. Options are gradle, maven, sbt. (Default is gradle)"
        required: false
        type: string
        default: "gradle"
      integration-tests:
        description: "If true, the action is executing integration tests (Default is true)"
        required: false
        type: boolean
        default: true
      docker-publisher:
        description: "Publisher to prefix docker image."
        required: false
        type: string
      working-directory:
        description: "The working directory of your Gradle artifacts. (Default is root directory)"
        required: false
        type: string
        default: "./"
    secrets:
      sonar-token:
        description: "Token for sonarcloud."
        required: true
      signing-secret-key-ring:
        description: "Key ring file for signing the sonatype publication."
        required: true
      signing-key-id:
        description: "Key id for signing the sonatype publication."
        required: true
      signing-password:
        description: "Password for signing the sonatype publication."
        required: true
      ossrh-username:
        description: "Username for signing into sonatype repository."
        required: true
      ossrh-password:
        description: "Password for signing into sonatype repository."
        required: true
      docker-username:
        description: "Username for docker authentication."
        required: false
      docker-password:
        description: "Password for docker authentication."
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        uses: bakdata/ci-templates/actions/java-gradle-build@feature/java-gradle
        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Test
        uses: bakdata/ci-templates/actions/java-gradle-test@feature/java-gradle
        with:
          integration-tests: true
          sonar-token: ${{ secrets.sonar-token }}
          signing-secret-key-ring: ${{ secrets.signing-secret-key-ring }}
          signing-key-id: ${{ secrets.signing-key-id }}
          signing-password: ${{ secrets.signing-password }}   
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}       
          working-directory: ${{ inputs.working-directory }}

  build-jib:
    name: Build Jib Image
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Build Jib Image
        uses: bakdata/ci-templates/actions/java-gradle-build-jib-image@feature/java-gradle
        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}

  publish:
    name: Publish
    runs-on: ubuntu-22.04
    needs: build-jib

    steps:
      - name: Publish
        uses: bakdata/ci-templates/actions/java-gradle-publish@feature/java-gradle
        with:
          signing-secret-key-ring: ${{ secrets.signing-secret-key-ring }}
          signing-key-id: ${{ secrets.signing-key-id }}
          signing-password: ${{ secrets.signing-password }}
          ossrh-username: ${{ secrets.ossrh-username }}
          ossrh-password: ${{ secrets.ossrh-password }}
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}

  publish-jib-image:
    name: Publish Jib Image
    runs-on: ubuntu-22.04
    needs: build-jib

    steps:
    - name: Publish jib image
      uses: bakdata/ci-templates/actions/docker-publish@feature/java-gradle
      with:
        publisher: ${{ inputs.docker-publisher }}
        username: ${{ secrets.docker-username }}
        password: ${{ secrets.docker-password }}        

  release:
    name: Create Github release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: publish
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            '**/build/libs/*.jar'
