name: Reusable workflow for building and publishing java gradle artifacts

on:
  workflow_call:
    inputs:
      java-distribution:
        description: "The java distribution to be installed. (Default is temurin)"
        required: false
        type: string
        default: "temurin"
      java-version:
        description: "The java version to be installed. (Default is 11)"
        required: false
        type: string
        default: "11"
      gradle-version:
        description: "The gradle version to be installed. (Default is 6.7.1)"
        required: false
        type: string
        default: "6.7.1"
      gradle-cache:
        description: "The gradle cache to use. Options are gradle, maven, sbt. (Default is gradle)"
        required: false
        type: string
        default: "gradle"
      integration-tests:
        description: "If true, the action is executing integration tests (Default is true)"
        required: false
        type: boolean
        default: true
      working-directory:
        description: "The working directory of your Gradle artifacts. (Default is root directory)"
        required: false
        type: string
        default: "./"
    secrets:
      sonar-token:
        description: "Token for sonarcloud."
        required: true
      signing-secret-key-ring:
        description: "Key ring file for signing the sonatype publication."
        required: true
      signing-key-id:
        description: "Key id for signing the sonatype publication."
        required: true
      signing-password:
        description: "Password for signing the sonatype publication."
        required: true
      ossrh-username:
        description: "Username for signing into sonatype repository."
        required: true
      ossrh-password:
        description: "Password for signing into sonatype repository."
        required: true
      gradle-publish-key:
        description: "Key for publishing to gradle plugin portal."
        required: true
      gradle-publish-secret:
        description: "Secret for publishing to gradle plugin portal."
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        uses: bakdata/ci-templates/actions/java-gradle-build@feature/java-gradle
        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Test
        uses: bakdata/ci-templates/actions/java-gradle-test@feature/java-gradle
        with:
          integration-tests: true
          sonar-token: ${{ secrets.sonar-token }}
          signing-secret-key-ring: ${{ secrets.signing-secret-key-ring }}
          signing-key-id: ${{ secrets.signing-key-id }}
          signing-password: ${{ secrets.signing-password }}   
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}       
          working-directory: ${{ inputs.working-directory }}

  publish:
    name: Publish
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Publish
        uses: bakdata/ci-templates/actions/java-gradle-publish@feature/java-gradle
        with:
          signing-secret-key-ring: ${{ secrets.signing-secret-key-ring }}
          signing-key-id: ${{ secrets.signing-key-id }}
          signing-password: ${{ secrets.signing-password }}
          ossrh-username: ${{ secrets.ossrh-username }}
          ossrh-password: ${{ secrets.ossrh-password }}
          gradle-publish-key: ${{ secrets.gradle-publish-key }}
          gradle-publish-secret: ${{ secrets.gradle-publish-secret }}
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
          working-directory: ${{ inputs.working-directory }}
  
  release:
    name: Create Github release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: publish
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Setup git
        run: |
          git config user.email ${{ secrets.github-email }}
          git config user.name ${{ secrets.github-username }}
        shell: bash

      - name: Set up Gradle with version ${{ inputs.gradle-version }}
        uses: bakdata/ci-templates/actions/java-gradle-setup@feature/java-gradle
        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-cache: ${{ inputs.gradle-cache }}
      
      - name: Generate changelog
        run: ./gradlew -Pchangelog.releaseVersion=${GITHUB_REF##*/} -Pchangelog.sinceTag=${GITHUB_REF##*/} --stacktrace --info generateChangelog
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_USER: ${{ secrets.github-username }}
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Debug
        run: cat CHANGELOG.md
        shell: bash

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            '**/build/libs/*.jar'
