name: Java Gradle Release
# Reusable workflow for releasing Java gradle projects

on:
  workflow_call:
    inputs:
      release-type:
        description: "Scope of the release (major, minor or patch)."
        required: true
        type: string
      java-distribution:
        description: "Java distribution to be installed. (Default is microsoft)"
        required: false
        type: string
        default: "microsoft"
      java-version:
        description: "Java version to be installed. (Default is 11)"
        required: false
        type: string
        default: "11"
      gradle-version:
        description: "Gradle version to be installed. (Default is wrapper)"
        required: false
        type: string
        default: "wrapper"
      working-directory:
        description: "Working directory of your Gradle artifacts. (Default is root directory)"
        required: false
        type: string
        default: "./"
    secrets:
      github-username:
        description: "GitHub username for committing the changes."
        required: true
      github-email:
        description: "GitHub email for committing the changes."
        required: true
      github-token:
        description: "GitHub token for committing the changes."
        required: true

    # Map the workflow outputs to job outputs
    outputs:
      old-version:
        description: "The old tag."
        value: ${{ jobs.release.outputs.old-version }}
      release-version:
        description: "The release tag."
        value: ${{ jobs.release.outputs.release-version }}

jobs:
  release:
    name: Release
    needs: evaluate-version
    runs-on: ubuntu-22.04

    # Map the job outputs to step outputs
    outputs:
      old-version: ${{ steps.evaluate-version.outputs.old-version }}
      release-version: ${{ steps.evaluate-version.outputs.release-version }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.github-token }}

      - name: Setup git
        run: |
          git config user.email ${{ secrets.github-email }}
          git config user.name ${{ secrets.github-username }}
        shell: bash

      - name: Setup semver
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
          semver --version
          exit 1

      - name: Bump version
        id: evaluate-version
        run: |
          old_version=$(grep "version=" gradle.properties | cut -d "=" -f2)
          release_version=$(semver bump ${{ inputs.release-type }} ${old_version})
          echo ::set-output name=release-version::$old_version
          echo ::set-output name=release-version::$release_version

      - name: Set up Gradle with version ${{ inputs.gradle-version }}
        uses: bakdata/ci-templates/actions/java-gradle-setup@feature/java-gradle
        with:
          java-distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}
      
      - name: Generate changelog
        run: ./gradlew -Pchangelog.releaseVersion=${{ needs.evaluate-version.outputs.release-version }} --stacktrace --info generateChangelog
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        env:
          GITHUB_USER: ${{ secrets.github-username }}
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: Commit and push
        run: |
          git commit -am "Changelog for version ${{ needs.evaluate-version.outputs.release-version }}" 
          git push
        shell: bash
      
      - name: Create release
        run: ./gradlew -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ needs.evaluate-version.outputs.release-version }} --stacktrace --info release -x test
        shell: bash
        working-directory: ${{ inputs.working-directory }}
