name: Lint

on:
  pull_request:

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      # TODO: use tag after v1.6.11 is released
      - name: Check workflow files
        run: |
            echo "::add-matcher::.github/actionlint-matcher.json"
            bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/77d8de2/scripts/download-actionlint.bash)
            ./actionlint -color
