name: Lint

on:
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Lint actions and workflows
        uses: bakdata/ci-templates/actions/action-lint@838fc43bf3cdd82b253a21c2f98157b449c7253b
        with:
          ref: "${{ github.event.pull_request.base.ref }}"
