name: Reusable workflow for building and publishing Python packages to TestPyPI or PyPI

on:
  workflow_call:
    inputs:
      release-type:
        description: "Scope of the release; See: https://python-poetry.org/docs/cli/#version"
        required: true
        type: string
      ref:
        description: "The ref name to checkout the repository."
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
      python-version:
        description: "The Python version for setting up Poetry. (Default is 3.10)"
        required: false
        default: "3.10"
        type: string
      poetry-version:
        description: "The Python version for setting up Poetry. (Default is 1.1.12)"
        required: false
        default: "1.1.12"
        type: string
      publish-to-test:
        description: "If set to false, the package is published to PyPI. (Default is true)"
        required: false
        default: true
        type: boolean
      working-directory:
        description: "The working directory of your Python package. (Default is root directory)"
        required: false
        default: "./"
        type: string
    secrets:
      github-username:
        description: "The GitHub username for committing the changes."
        required: true
      github-email:
        description: "The GitHub email for committing the changes."
        required: true
      github-token:
        description: "The GitHub token for committing the changes."
        required: true
      pypi-token:
        description: "The PyPI token for publishing packages."
        required: true

    # Map the workflow outputs to job outputs
    outputs:
      release-version:
        description: "The bumped version of the package."
        value: ${{ jobs.create-release.outputs.release-version }}
      old-version:
        description: "The old version of the package."
        value: ${{ jobs.create-release.outputs.old-version }}

jobs:
  create-release:
    runs-on: ubuntu-22.04
    # Map the job outputs to step outputs
    outputs:
      release-version: ${{ steps.bump-version.outputs.release-version }}
      old-version: ${{ steps.bump-version.outputs.old-version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false # required for pushing to protected branch later

      - name: Bump version with Poetry
        id: bump-version
        uses: bakdata/ci-templates/actions/python-poetry-bump-version@v1.18.2
        with:
          release-type: ${{ inputs.release-type }}
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Release to PyPI
        uses: bakdata/ci-templates/actions/python-poetry-release@v1.18.2
        with:
          pypi-token: ${{ secrets.pypi-token }}
          publish-to-test: ${{ inputs.publish-to-test }}
          working-directory: ${{ inputs.working-directory }}
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}

      - name: Commit and push pyproject.toml file
        uses: bakdata/ci-templates/actions/commit-and-push@v1.0.0
        with:
          ref: ${{ inputs.ref }}
          commit-message: "Bump version ${{ steps.bump-version.outputs.old-version }} → ${{ steps.bump-version.outputs.release-version }}"
          github-username: ${{ secrets.github-username }}
          github-email: ${{ secrets.github-email }}
          github-token: ${{ secrets.github-token }}
