name: Reusable workflow for releasing tag versions

on:
  workflow_call:
    inputs:
      version-configs-dir:
        description: "The Path to the directory containing the file where the versioning is defined and `.bumpversion.cfg` file."
        required: true
        type: string
      versioning-file:
        description: "The name of the file where the version is declared (E.g: Dockerfile, Chart.yaml ). This file is also specified in the `.bumpversion.cfg` "
        required: true
        type: string
      release-type:
        description: "Scope of the release (major, minor or patch)."
        required: true
        type: string
      next-dev-release-type:
        description: "Scope of the next release (minor or patch) for developers"
        required: true
        type: string
      next-dev-release-suffix:
        description: "The suffix to add for the developer version"
        required: false
        default: "SNAPSHOT"
        type: string
    secrets:
      github-email:
        description: "The GitHub email for committing the changes."
        required: true
      github-username:
        description: "The GitHub username for committing the changes."
        required: true
      github-token:
        description: "The GitHub token for committing the changes."
        required: true

jobs:
  bump_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out default branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github-token }}

      - name: Verify current version
        if: ${{ inputs.release-type == 'patch'}}
        id: suffixstep
        run: |
          VERSION_VAR=`sed -n 's/^current_version = \(.*\)/\1/p' < .bumpversion.cfg`
          DEV_SUFFIX=${{ inputs.next-dev-release-suffix }}
          echo "!!!!!!!!!!!!!!!!!!!!!!!"
          echo $VERSION_VAR
          echo $DEV_SUFFIX
          echo "!!!!!!!!!!!!!!!!!!!!!!!"
          
          if [[ $VERSION_VAR == *$DEV_SUFFIX* ]]; then
            final=${$VERSION_VAR%$DEV_SUFFIX}
            echo "has_suffix=true" >> "$GITHUB_OUTPUT"
            echo "version_var=$final" >> "$GITHUB_OUTPUT"
            echo "////////////////////////"
            echo $final
            echo "////////////////////////"
          else
            echo "has_suffix=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Bump version when release type is 'patch' and current version contains dev suffix
        if: ${{ inputs.release-type == 'patch'}} && ${{ steps.suffixstep.outputs.has_suffix == true}}
        id: release-with-suffix
        uses: bakdata/ci-templates/actions/bump-version@feat/tag-release
        with:
          release-type: ${{ inputs.release-type }}
          working-directory: ${{ inputs.version-configs-dir }}
          new-version: ${{ steps.suffixstep.outputs.version_var }}

      - name: Bump version when release type is not 'patch' or suffix is empty
        if: ${{ inputs.release-type != 'patch'}} || ! ${{ steps.suffixstep.outputs.has_suffix == false}}
        id: release-without-suffix
        uses: bakdata/ci-templates/actions/bump-version@feat/tag-release
        with:
          release-type: ${{ inputs.release-type }}
          working-directory: ${{ inputs.version-configs-dir }}

      - name: Verify which of the steps above has been excecuted and return the release Tag
        id: get-release
        run: |
          tagwithout = ${{ steps.release-without-suffix.outcome }}
          tagwith = ${{ steps.release-with-suffix.outcome }}
          if ["${tagwithout}" == "success"]; then
            echo "release-tag=${{ steps.release-without-suffix.outputs.old-tag }}" >> "$GITHUB_OUTPUT"
          elif ["${tagwith}" == "success"]; then
            echo "release-tag=${{ steps.release-with-suffix.outputs.old-tag }}" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Commit and push the file where the versioning is defined & .bumpversion.cfg file to release new tag
        uses: bakdata/ci-templates/actions/commit-and-push@v1.6.0
        with:
          commit-message: "Bump version and create release version ${{ steps.get-release.outputs.release-tag }}"
          github-username: ${{ secrets.github-username }}
          github-email: ${{ secrets.github-email }}
          github-token: ${{ secrets.github-token }}

      - name: Create and push new Tag
        run: |
          tag=${{ steps.get-release.outputs.release-tag }}
          message='Create new Tag: ${tag}'
          git config user.name "${{ secrets.github-username }}"
          git config user.email "${{ secrets.github-email }}"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
        shell: bash
        working-directory: ${{ inputs.version-configs-dir }}

      - name: Setup semver
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/3.3.0/src/semver
          chmod +x /usr/local/bin/semver

      - name: Sembump dev-version
        id: sembump
        run: |
          tag=${{ steps.get-release.outputs.release-tag }}
          release_version=$(semver bump "${{ inputs.next-dev-release-type }}" "${tag}")
          echo "version=$release_version" >> "$GITHUB_OUTPUT"

      - name: Bump to "tag-${{ inputs.next-dev-release-suffix }}" version
        uses: bakdata/ci-templates/actions/bump-version@feat/tag-release
        with:
          release-type: ${{ inputs.next-dev-release-type }}
          working-directory: ${{ inputs.version-configs-dir }}
          new-version: ${{ steps.sembump.outputs.version }}-${{ inputs.next-dev-release-suffix }}

      - name: Commit and push the file where the versioning is defined & .bumpversion.cfg file (containing the -${{ inputs.next-dev-release-suffix }} version)
        uses: bakdata/ci-templates/actions/commit-and-push@v1.6.0
        with:
          commit-message: "Bump version and create dev version ${{ steps.get-release.outputs.release-tag }} → ${{ steps.sembump.outputs.version }}-${{ inputs.next-dev-release-suffix }}"
          github-username: ${{ secrets.github-username }}
          github-email: ${{ secrets.github-email }}
          github-token: ${{ secrets.github-token }}
